# -*- coding: utf-8 -*-
"""FQG_runner.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DRUa3PH-0u5oU37i-k1eWYQbM0BPySzx

<p><img alt="UdeA logo" style="height: 180px !important; width: auto;" src="https://upload.wikimedia.org/wikipedia/commons/archive/f/fb/20161010213812%21Escudo-UdeA.svg" align="right" hspace="10px" vspace="0px"></p>


<h1> <b>Laboratorio 01 pinguinos - runner.py

Física Computacional II 2026-2</b> </h1>

</div>

<!-- <br> le permite hacer espacios -->
<br>

<hr size=10 noshade color="green">
<p>


<div align="left">       

<h3><i><b>Felipe Quitian Gallego</b><br>  
Universidad de Antioquia <br>
Instituto de Física  <br>
</i></h3>
</div>

## Librerias
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import json
import os

"""# Pingüinos

## Fase OBSERVE
"""

# Crear carpeta de artifacts
os.makedirs('artifacts', exist_ok=True)

# Cargar el dataset
df = sns.load_dataset('penguins')

# 1. Esquema y Dimensiones
forma = {'filas': df.shape[0], 'columnas': df.shape[1]}
tipos_datos = df.dtypes.astype(str).to_dict()

# 2. Calidad Inicial de Datos
valores_nulos = df.isnull().sum().to_dict()
filas_duplicadas = int(df.duplicated().sum())

# 3. Perfilado Estadístico
# Variables numéricas
estadisticas_numericas = df.describe().to_dict()

# Variables categóricas
estadisticas_categoricas = {}
for columna in df.select_dtypes(include=['object', 'category']).columns:
    estadisticas_categoricas[columna] = df[columna].value_counts().to_dict()

# 4. Muestra Estructural (primeras 5 filas)
datos_muestra = df.head(5).to_dict(orient='records')

# Consolidar todo en un diccionario estructurado
perfil_pinguinos = {
    'esquema_y_dimensiones': {
        'forma': forma,
        'tipos_datos': tipos_datos
    },
    'calidad_de_datos': {
        'valores_nulos': valores_nulos,
        'filas_duplicadas': filas_duplicadas
    },
    'perfilado_estadistico': {
        'numericas': estadisticas_numericas,
        'categoricas': estadisticas_categoricas
    },
    'muestra_estructural': datos_muestra
}

# Guardar el diccionario como un archivo JSON
archivo_salida = 'artifacts/00_raw_profile.json'
with open(archivo_salida, 'w', encoding='utf-8') as f:
    json.dump(perfil_pinguinos, f, indent=4, ensure_ascii=False)

"""## Fase DESCRIBE"""

# Crear carpeta de artifacts (por si se ejecuta de forma independiente)
os.makedirs('artifacts', exist_ok=True)

# Cargar el dataset y limpiar nulos
df = sns.load_dataset('penguins')
df_clean = df.dropna()

# Diccionario para almacenar el registro visual
visual_registry = {}

# --- Generación de Gráficos ---

# 1. Histogramas
fig, axes = plt.subplots(2, 2, figsize=(12, 10))
axes = axes.flatten()
numeric_cols = ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']
for i, col in enumerate(numeric_cols):
    sns.histplot(df_clean[col], kde=True, ax=axes[i])
    axes[i].set_title(f'Distribución de {col}')
plt.tight_layout()
plt.savefig('artifacts/01_histograms.png')
visual_registry['01_histograms.png'] = "Distribución univariada de las variables numéricas (largo y profundidad de pico, largo de aleta y masa corporal)."
plt.close()

# 2. Countplots
fig, axes = plt.subplots(1, 3, figsize=(15, 5))
cat_cols = ['species', 'island', 'sex']
for i, col in enumerate(cat_cols):
    sns.countplot(x=col, data=df_clean, ax=axes[i], hue=col, legend=False)
    axes[i].set_title(f'Conteo de {col}')
plt.tight_layout()
plt.savefig('artifacts/02_countplots.png')
visual_registry['02_countplots.png'] = "Conteo de frecuencias para variables categóricas (especie, isla y sexo)."
plt.close()

# 3. Pairplot
pairplot_fig = sns.pairplot(df_clean, hue='species')
pairplot_fig.savefig('artifacts/03_pairplot.png')
visual_registry['03_pairplot.png'] = "Matriz de dispersión multivariada coloreada por especie."
plt.close()

# 4. Boxplots
fig, axes = plt.subplots(1, 2, figsize=(14, 6))
sns.boxplot(x='species', y='body_mass_g', hue='sex', data=df_clean, ax=axes[0])
axes[0].set_title('Body Mass vs Species')
sns.boxplot(x='species', y='flipper_length_mm', hue='sex', data=df_clean, ax=axes[1])
axes[1].set_title('Flipper Length vs Species')
plt.tight_layout()
plt.savefig('artifacts/04_boxplots.png')
visual_registry['04_boxplots.png'] = "Distribución de masa corporal y largo de aleta separada por especie y sexo."
plt.close()

# 5. Heatmap de Correlación
numeric_df = df_clean.select_dtypes(include=['float64', 'int64'])
corr_matrix = numeric_df.corr()
plt.figure(figsize=(8, 6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', vmin=-1, vmax=1, fmt='.2f')
plt.title('Matriz de Correlación')
plt.tight_layout()
plt.savefig('artifacts/05_correlation_heatmap.png')
visual_registry['05_correlation_heatmap.png'] = "Mapa de calor mostrando la correlación de Pearson entre las variables numéricas."
plt.close()

# Guardar el registro visual
with open('artifacts/05_visual_registry.json', 'w', encoding='utf-8') as f:
    json.dump(visual_registry, f, indent=4, ensure_ascii=False)


# --- Generación de Estadísticas Descriptivas ---

# Tablas cruzadas para encontrar patrones categóricos
crosstab_species_island = pd.crosstab(df_clean['species'], df_clean['island']).to_dict()
crosstab_species_sex = pd.crosstab(df_clean['species'], df_clean['sex']).to_dict()

# Compilar todo en un único JSON
descriptive_stats = {
    'correlaciones_numericas': corr_matrix.to_dict(),
    'tablas_cruzadas_categoricas': {
        'especie_vs_isla': crosstab_species_island,
        'especie_vs_sexo': crosstab_species_sex
    }
}

# Guardar estadísticas descriptivas
with open('artifacts/04_descriptive_stats.json', 'w', encoding='utf-8') as f:
    json.dump(descriptive_stats, f, indent=4, ensure_ascii=False)

"""## Fase HYPOTHESIZE AND CONCLUDE"""

import json
import os

# Asegurar que la carpeta artifacts existe
os.makedirs('artifacts', exist_ok=True)

# Respuesta literal generada por el Agente
respuesta_agente = {
  "hipotesis_falsables": [
    "H1: La especie de un pingüino puede ser clasificada con alta precisión utilizando únicamente la longitud de la aleta y la profundidad del pico, dado que forman clústeres morfológicos claramente separados.",
    "H2: La distribución bimodal general observada en la longitud de la aleta y la masa corporal es causada exclusivamente por las diferencias morfológicas de la especie Gentoo frente a Adelie y Chinstrap.",
    "H3: Dado el dimorfismo sexual evidente, es posible predecir el sexo de un pingüino basándose en su masa corporal, asumiendo que los machos siempre presentan una masa superior a la mediana de las hembras dentro de su respectiva especie."
  ],
  "conclusiones_descriptivas": [
    "Existe una fuerte correlación lineal positiva de 0.87 entre la longitud de la aleta y la masa corporal de los pingüinos, siendo la relación más fuerte de todo el dataset.",
    "Se evidencia un claro dimorfismo sexual en todas las especies estudiadas: los machos tienen consistentemente mayor masa corporal y aletas más largas que las hembras de su misma especie.",
    "La especie Gentoo se distingue marcadamente de las demás por tener la mayor masa corporal y longitud de aleta, pero presenta la menor profundidad de pico promedio.",
    "Las especies Adelie y Chinstrap tienen distribuciones similares en masa corporal y longitud de aleta, pero divergen significativamente en la longitud del pico, siendo notablemente mayor en la especie Chinstrap.",
    "Adelie es la especie dominante en términos de frecuencia poblacional y la única con registro de presencia en las tres islas (Biscoe, Dream, Torgersen)."
  ],
  "preguntas_para_runner": [
    "¿Contamos con datos adicionales sobre las características ambientales de las islas que nos ayuden a explicar la exclusión territorial, como por qué Gentoo y Chinstrap no coexisten en la isla Dream o Biscoe?",
    "Se detectaron valores atípicos (outliers) en los diagramas de caja, como especímenes de Chinstrap con aletas muy cortas o Gentoo con masa atípica. ¿Deseas aislar estos registros mediante código para evaluar si son errores de medición?",
    "Basado en la clara separación de las características, ¿es pertinente avanzar a una fase predictiva (MODELING) para entrenar un modelo de clasificación que deduzca la especie a partir de mediciones físicas?"
  ]
}

# 1. Guardar artifacts/06_hypotheses_log.json
with open('artifacts/06_hypotheses_log.json', 'w', encoding='utf-8') as f:
    json.dump({"hipotesis_falsables": respuesta_agente["hipotesis_falsables"]}, f, indent=4, ensure_ascii=False)

# 2. Guardar artifacts/07_conclusions.json
with open('artifacts/07_conclusions.json', 'w', encoding='utf-8') as f:
    json.dump({"conclusiones_descriptivas": respuesta_agente["conclusiones_descriptivas"]}, f, indent=4, ensure_ascii=False)

# 3. Guardar artifacts/09_questions.json
with open('artifacts/09_questions.json', 'w', encoding='utf-8') as f:
    json.dump({"preguntas_para_runner": respuesta_agente["preguntas_para_runner"]}, f, indent=4, ensure_ascii=False)

"""# Comparación entre el enfoque clasico y el enfoque con agentes

Despues de obtener los resultados y la automatizacion para diferentes datasets podemos observar que los resultados obtenidos con el agente son muy parecidos a los obtenidos desde el enfoque clasico, y lo mas importante es la reducción en el tiempo de trabajo y la eficiencia en el codigo, el desarrollo clasico tomo mucho tiempo y muchas lineas de codigo para poder ser implementado, el enfoque con agentes fue mas al grano y mas ordenado con los archivos obtenidos al final.

Sim embargo siempre se debe tener cuidado con el analisis de la información, aunque el agente procese mas rapido los datos no siempre lo hace de forma acertiva y puede generar errores, en analisis de los datos y sus implicaciones biologicas, geograficas, poblacionales y demas posibles consecuencias sobre la vida en la tierra deben ser siempre verificadas por un humano competente en el tema ya que este es el unico que posee la experiencia de la vida, cosa que un agente de IA nunca podra experimentar.
"""

